name: release .nupkg's

on:
  push:
    tags: 
        '*' 
permissions:
  contents: write

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  PACKAGE_VERSION: '1.2.14.100'
jobs:
  call-build-workflow:
    uses: ./.github/workflows/build.yaml
  release:
    needs: call-build-workflow
    runs-on: macos-13
    name: Release
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Download Artifacts
        run: ls -R
      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
            draft: false
            prerelease: false
            release_name: ${{ github.ref }}
            tag_name: ${{ github.ref }}
            body_path: ${{ github.workspace }}/CHANGELOG.md
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload .nupkg 
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ github.workspace }}/libpjsua2.maui.${{ env.PACKAGE_VERSION }}.nupkg
            asset_name: libpjsua2.maui.${{ env.PACKAGE_VERSION }}.nupkg
            asset_content_type: application/zip